apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-monitor-sa
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metrics-monitor
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-monitor
  namespace: spark
subjects:
  - kind: ServiceAccount
    name: metrics-monitor-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: metrics-monitor
  apiGroup: rbac.authorization.k8s.io

