---
- hosts: kubernetes-master-node
  become: yes
  #become_user: root
  vars_files:
    - env_variables
  gather_facts: no
  tasks:
  - name: Build Docker images
    shell: |
      sudo docker build -f spark-code/Dockerfile -t nikoshet/k8s-spark:spark-cherry-update . > ../echo-build-spark-code.txt 2>&1
    # /dev/tcp/localhost/4000 2>&1 #+nc -lk 4000
    args:
      chdir: "{{ HOME }}/cherry-shuffle-service-spark/"

  - name: Push Docker images
    shell: |
      sudo docker push nikoshet/k8s-spark:spark-cherry-update > ../echo-push-spark-code.txt 2>&1 #thread
    args:
      chdir: "{{ HOME }}/cherry-shuffle-service-spark/"