---
- hosts: all
  become: yes
  #become_user: root
  gather_facts: no
  vars_files:
    - env_docker_variables
  tasks:
  - name: Install Python Docker module
    shell: |
      export LC_ALL=C
      sudo pip3 uninstall docker docker-py -y
      sudo pip3 install docker

  - name: Log into DockerHub
    docker_login:
      #registry: "{{ registry }}"
      username: "{{ username }}"
      password: "{{ password }}"
      email: "{{ email }}"