---
- import_playbook: playbooks/setup_hosts_and_disable_swap.yml
- import_playbook: playbooks/ssh_key_setup.yml
- import_playbook: playbooks/general_installations.yml
- import_playbook: playbooks/kubernetes_installations.yml