apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-metadata-service
  labels:
    component: spark-metadata-service
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-metadata-service
  template:
    metadata:
      labels:
        component: spark-metadata-service
    spec:
      containers:
        - name: spark-metadata-service
          image:  nikoshet/k8s-spark:spark-cherry
          imagePullPolicy: Never #IfNotPresent #Never
          command: ["/spark/spark-metadata-service.sh"]
          #command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
          ports:
            - containerPort: 5555
          resources:
            requests:
              cpu: 0.5
              memory: 1Gi
            limits:
              #cpu: "0.5"
              memory: 1.5Gi
      nodeSelector:
        type: master-driver